/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:156e3743-4d49-4d14-8871-d7dbfbbc4c47",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_HdYD6ueK4",
    "aws_user_pools_web_client_id": "7um1h6qbvhvi5timtfco0gn3ai",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pdzmdjbdevdy3n4fecjn2hz6re.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
